### ISSUE TITLE
(minor) URL parse regexp not allow "http://localhost:8080" (url without domain)

### ISSUE THREAD

**Issue by ToGL** [testit-tms/importers#21]
testit-importer-allure/src/configurator.py:242 - wont allow url without domain
testit -u http://localhost:8080 fails with "Wrong URL"

workaround use: http://127.0.0.1:8080

**Comment by testit-owner** [comment]
Good afternoon!
This bug has been fixed in the package version 1.2.4 https://github.com/testit-tms/importers/pull/23.
Thank you for contacting us!
