### ISSUE TITLE
Команда testit --resultsdir не существует

### ISSUE THREAD

**Issue by saneci** [testit-tms/importers#37]
**Шаги воспроизведения**

1. установить testit-api-client по [инструкции](https://github.com/testit-tms/importers/tree/main/testit-importer-allure#installation)
2. выполнить команду `testit --resultsdir allure-results`

**Ожидаемый результат:** команда выполнена успешно, ошибок нет

**Фактический результат:** ошибка 

```bash
usage: testit [options]
testit: error: unrecognized arguments: --resultsdir allure-results
```

**Comment by ABolikov** [comment]
Добрый день, 1 пункт в шагах вводит в заблжуение: "установить testit-api-client" - так вот testit-api-client это отдельная библиотека для работы с API TestIt. Инструкция же ведет на https://github.com/testit-tms/importers/tree/main/testit-importer-allure#installation. Отсюда вопрос, что по итогу было установлено?

У себя впоровзести ни как не полчается. Укажите пожалста версию кторую устанавливаете.
