### ISSUE TITLE
Error during import result: "TestRunV2GetModel has no attribute 'customParameters' at ['received_data']['customParameters']"

### ISSUE THREAD

**Issue by YaPopkov** [testit-tms/importers#65]
testit-api-client == "3.3.0"
testit-importer-allure == "1.6.0"

До 20.05.2024 результаты прогонов удачно импортировались в TMS, после посыпалась такая ошибка.

Предпринятые шаги для починки: обновление обеих библиотек до актуального состояния, как итог не может найти путь до результатов (внезапно). 

Хардкод путей к результатам приводит к тому, что джоба проходит успешно, но результаты не импортируются в TestIT, есть запись о прогоне в TMS, но пустая (0 тестов) и статус "в очереди".
![image](https://github.com/testit-tms/importers/assets/100370339/134f6fe8-c350-4489-a84d-2c8dc0097185)

**Comment by komissarov-petr** [comment]
@YaPopkov Проверьте версию TestIT. [Таблица ](https://github.com/testit-tms/api-client-python?tab=readme-ov-file#compatibility) совместимости версий клиента.
